### ISSUE TITLE
IIS

### ISSUE THREAD

**Issue by dawidsouza** [thebitnomad/Daybreak-Online-AIO#1]
Estou tendo dificuldades em configurar o IIS, a aplicação não conecta ao mysql local.
apresenta o seguinte
[MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.]    MySql.Data.MySqlClient.NativeDriver.Open() +1233    MySql.Data.MySqlClient.Driver.Open() +58    MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings) +180    MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection() +11    MySql.Data.MySqlClient.MySqlPool.GetPooledConnection() +257    MySql.Data.MySqlClient.MySqlPool.TryToGetDriver() +117    MySql.Data.MySqlClient.MySqlPool.GetConnection() +102    MySql.Data.MySqlClient.MySqlConnection.Open() +325    Saturn.Tools.Master.SMaster.UpdateDatabase() +156    Saturn.Tools.Master.SMaster.Startup() +28    ASP.global_asax.Application_Start(Object sender, EventArgs e) +559  [HttpException (0x80004005): Unable to connect to any of the specified MySQL hosts.]    System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +2769014    System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +128    System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +188    System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +295    System.Web.HttpApplicationFactory.GetPipelineApplicationInstance(IntPtr appContext, HttpContext context) +56    System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +231  [HttpException (0x80004005): Unable to connect to any of the specified MySQL hosts.]    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9007971    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +85    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +333

e  no servidor não aparece nenhuma tentativa de conexão da aplicação com o usuario definido

**Comment by thanhle19921993** [comment]
thebitnomad my dear bro !!! i have issues aboue EXTJS ...plz help me !! i can't file folder extjs in source masterweb !! plz check !! hope the best for u !

**Comment by Av3z** [comment]
Foi feita algumas modificações no passo a passo do readme. da uma olhada ali vê se não está faltando nenhum processo.

**Comment by Av3z** [comment]
> 

Foi feita algumas modificações no passo a passo do readme. da uma olhada ali vê se não está faltando nenhum processo.

**Comment by thanhle19921993** [comment]
> > 
> 
> Foi feita algumas modificações no passo a passo do readme. da uma olhada ali vê se não está faltando nenhum processo.

bro!! can i ask about the issues extjs ? plz i need help ,

**Comment by dawidsouza** [comment]
consegui resolver esse erro ja tem um tempo fiquei empacado nele uns 2 dias kkk

**Comment by Av3z** [comment]
> > > 
> > 
> > 
> > Foi feita algumas modificações no passo a passo do readme. da uma olhada ali vê se não está faltando nenhum processo.
> 
> bro!! can i ask about the issues extjs ? plz i need help ,

U need change for classic in IIS and Version 2.0

**Comment by Av3z** [comment]
> consegui resolver esse erro ja tem um tempo fiquei empacado nele uns 2 dias kkk

Mano me manda seu discord ou me add : av3z

**Comment by dawidsouza** [comment]
tu ja ta falando cmg mano kkk sou o drako

**Comment by thebitnomad** [comment]
Solved

**Comment by thebitnomad** [comment]
Solved.
